apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinecone-pvc
  namespace: llama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
