apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaindex
  namespace: llama
  labels:
    app: llamaindex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llamaindex
  template:
    metadata:
      labels:
        app: llamaindex
    spec:
      containers:
      - name: llamaindex
        image: python:3.9-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install fastapi uvicorn pydantic pyyaml psycopg2-binary
            mkdir -p /app
            cp /app/config/main.py /app/main.py
            cd /app
            python -m uvicorn main:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: llamadb
        - name: PINECONE_HOST
          value: pinecone
        - name: PINECONE_PORT
          value: "6333"
        volumeMounts:
        - name: llamaindex-config
          mountPath: /app/config
        - name: llamaindex-data
          mountPath: /app/data
      volumes:
      - name: llamaindex-config
        configMap:
          name: llamaindex-config
      - name: llamaindex-data
        persistentVolumeClaim:
          claimName: llamaindex-pvc
